### PR TITLE
refactor: simplify api creation and calling 

### PR DESCRIPTION
**Pull request by richardaspinall**
### Description

- Refactored the api call logic to automatically take care of types when calling the api methods (now done via apiCall in front of FetchFacade)
- Simplified how an API is created. See: `ApiMethodMap.ts` and `routeConfig.ts`

### Task

[CU-86cue2ypy](https://app.clickup.com/t/86cue2ypy)

### Checklist

- [x] Added learning objectives to clickup task

### CODE REVIEW

**Comment by richardaspinall** [comment]
Task linked: [CU-86cue2ypy [FE] refactor fetch facade](https://app.clickup.com/t/86cue2ypy)

**Comment by richardaspinall** [comment]
@tommy-trombone this one will be rebased and merged after [your PR](https://github.com/richardaspinall/poker-react-node/pull/39)  as it will have conflicts that I will address 👍

**Comment by richardaspinall** [comment]
@tommy-trombone I've rebased on top of your work with player leaving table so you can review this when you're ready 👍

**Review by tommy-trombone — APPROVED** [review]
Love how abstract/clean this is now.

**Pull request merged**
