### PR TITLE
refactor: move room creation out of pokertable

### PR DESCRIPTION
**Pull request by tommy-trombone**
### Description

Decouple creating a room from creating a table for more flexibility.

### Task

[CU-86cubmxam](https://app.clickup.com/t/86cubmxam)

### Checklist

- [x] Added learning objectives to clickup task

### CODE REVIEW

**Comment by richardaspinall** [comment]
Task linked: [CU-86cubmxam [BE] move room calls from PokerTable](https://app.clickup.com/t/86cubmxam)

**Review by richardaspinall — CHANGES_REQUESTED** [review]
We actually want to move anything to do with Rooms from PokerTable, so there is also the `start_game` logic in the `sitAtTable` function that sends an event that the game is starting (the task was to move room calls from PokerTable not just creation). 

This is what is called a "side effect" as the function isn't `sitAtTableAndStartGame`. Which you could look at this whole task as removing side effects "anything to do with Rooms in the PokerTable"

https://github.com/richardaspinall/poker-react-node/blob/ba7d3c59d85b32cae1b928fc4bd33fc0e49e96a2/backend/src/game/PokerTable.ts#L54

Instead after `sitAtTable` is successful, we should do that either in the handler or I reckon better to move to the GameLobbyService and actually a lot of the code in the handlers should be moved there or some other service.

**Comment by richardaspinall** [comment]
Learning note:

We are doing this so that we have separation of concerns. We could swap out the implementation of the Rooms functionality and not have to touch the domain object: PokerTable

**Comment by tommy-trombone** [comment]
Hey @richardaspinall this branch got into a weird state when I rebased so I just created a new branch and moved my changes there. 

I've only moved the room logic into the jointable handler for now and we can maybe revisit moving it elsewhere down the line. It doesn't seem a quick and easy move into gamelobbyservice in my mind so I reckon we just leave it in joinhandler for now.

https://github.com/richardaspinall/poker-react-node/compare/move-room-functions-out-of-pokertable?expand=1

**Comment by richardaspinall** [comment]
Nice one!

**Pull request closed without merging**
