### PR TITLE
feat: Initial Games Bet endpoint

### PR DESCRIPTION
**Pull request by tommy-trombone**
Description

This endpoint is for making a bet

How to test

Just endpoint scaffolding/skeleton at the moment

Task
[CU-86cvbdgx6](https://app.clickup.com/t/86cvbdgx6)

### CODE REVIEW

**Comment by richardaspinall** [comment]
Task linked: [CU-86cvbdgx6 [BE] generate actions endpoints](https://app.clickup.com/t/86cvbdgx6)

**Review by richardaspinall — CHANGES_REQUESTED** [review]
This one doesn't seem to have been generated yet?

**Comment by tommy-trombone** [comment]
Oh yeah there was a bug in my games_bet file so the generate process broke. Should be good now.

**Comment by tommy-trombone** [comment]
I'm going to create a new branch because it's easier than untangling the merge conflicts when creating two endpoints at once. I should just do them one at a time in future.

**Pull request closed without merging**
